[package]
name = "matching-engine"
version = "0.1.0"
authors = ["Christian Hess <christianhess.rlz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
