[package]
name = "matching-engine"
version = "0.1.0"
authors = ["Christian Hess <christianhess.rlz@gmail.com>"]
edition = "2018"

[dependencies]


[[bin]]
path = "src/cli.rs"
name = "matching-engine-cli"
test = false
bench = false
